apiVersion: apps/v1
kind: Deployment
metadata:
  name: appdirect
  labels:
    app: appdirect
spec:
  selector:
    matchLabels:
      app: appdirect
  template:
    metadata:
      labels:
        app: appdirect
    spec:
      containers:
        - name: appdirect
          image: gcr.io/smar-proxy-839/cremerfc/appdirect
          envFrom:
          - configMapRef:
              name: example-config
          resources:
            limits:
              memory: '256Mi'
              cpu: '500m'
            requests:
              memory: '32Mi'
              cpu: '100m'

